# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Status1(Enum):
    """
    The status of the Report Schedule
    """
