# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Status2(Enum):
    """
    Status of the *Task*. (Note that users without advanced tasks can only have either complete or pending)
    """
