# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Status(Enum):
    """
    The current status of the *Matter*
    """
