# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class LightColor(Enum):
    """
    Accent color to complement the main calendar color.
    """
