from enum import Enum


class PracticeAreacreateJsonBodyDataCategory(str, Enum):
    ADMINISTRATIVE = "administrative"
    ADMIRALTY_AND_MARITIME = "admiralty_and_maritime"
    ANTI_TRUST_AND_COMPETITION = "anti_trust_and_competition"
    APPELLATE = "appellate"
    BANKING_AND_FINANCE = "banking_and_finance"
    BANKRUPTCY = "bankruptcy"
    BUSINESS_FORMATION_AND_COMPLIANCE = "business_formation_and_compliance"
    CIVIL_LITIGATION = "civil_litigation"
    CIVIL_RIGHTS_AND_CONSTITUTIONAL = "civil_rights_and_constitutional"
    COLLECTIONS_AND_DEBT = "collections_and_debt"
    COMMERCIAL_AND_SALE_OF_GOODS = "commercial_and_sale_of_goods"
    COMMERCIAL_LITIGATION = "commercial_litigation"
    CONSTRUCTION = "construction"
    CONSUMER_PROTECTION = "consumer_protection"
    CONTRACTS = "contracts"
    CORPORATE_LITIGATION = "corporate_litigation"
    CRIMINAL = "criminal"
    DISABILITY_AND_SOCIAL_SECURITY = "disability_and_social_security"
    EDUCATION = "education"
    ELDER = "elder"
    EMPLOYMENT_AND_LABOR = "employment_and_labor"
    ENERGY_AND_ENVIRONMENTAL = "energy_and_environmental"
    ETHICS = "ethics"
    FAMILY = "family"
    FOOD_AND_DRUG = "food_and_drug"
    GENERAL_PRACTICE = "general_practice"
    GOVERNMENT = "government"
    HEALTHCARE = "healthcare"
    IMMIGRATION = "immigration"
    INSURANCE = "insurance"
    INTELLECTUAL_PROPERTY = "intellectual_property"
    INTERNATIONAL = "international"
    IN_HOUSE_COUNSEL = "in_house_counsel"
    JUVENILE = "juvenile"
    LEGAL_AID = "legal_aid"
    MEDIATION_AND_ARBITRATION = "mediation_and_arbitration"
    MEDICAL_MALPRACTICE = "medical_malpractice"
    MILITARY = "military"
    MULTI_PRACTICE = "multi_practice"
    NON_PROFIT_AND_PRO_BONO = "non_profit_and_pro_bono"
    OTHER = "other"
    PERSONAL_INJURY = "personal_injury"
    PRIVACY_AND_INFORMATION_SECURITY = "privacy_and_information_security"
    PRIVATE_CLIENT = "private_client"
    PRODUCT_LIABILITY = "product_liability"
    REAL_ESTATE = "real_estate"
    SCIENCE_AND_TECHNOLOGY = "science_and_technology"
    SECURITIES_AND_MERGERS_AND_ACQUISITIONS = "securities_and_mergers_and_acquisitions"
    SMALL_CLAIMS = "small_claims"
    SPORTS_AND_ENTERTAINMENT_AND_GAMING = "sports_and_entertainment_and_gaming"
    TAX = "tax"
    TELECOMMUNICATIONS = "telecommunications"
    TRAFFIC_OFFENSES = "traffic_offenses"
    TRANSPORTATION = "transportation"
    TRIBAL = "tribal"
    TRUSTS = "trusts"
    WILLS_AND_ESTATES = "wills_and_estates"
    WORKERS_COMPENSATION = "workers_compensation"

    def __str__(self) -> str:
        return str(self.value)
