from enum import Enum


class ReportPresetcreateDataBodyDataKind(str, Enum):
    ACCOUNTS_RECEIVABLE = "accounts_receivable"
    ACCOUNTS_RECEIVABLE_AGING = "accounts_receivable_aging"
    BANK_ACCOUNT_ACTIVITY = "bank_account_activity"
    BILLING_HISTORY = "billing_history"
    BILLING_RATE = "billing_rate"
    CLIENT_ACTIVITY = "client_activity"
    CLIENT_LEDGER = "client_ledger"
    CLIO_PAYMENTS_DEPOSIT = "clio_payments_deposit"
    CLIO_PAYMENTS_LEDGER = "clio_payments_ledger"
    CLIO_PAYMENTS_MONTHLY_STATEMENT = "clio_payments_monthly_statement"
    CLIO_PAYMENTS_SALES_TAX = "clio_payments_sales_tax"
    CLIO_PAYMENTS_TRANSACTION = "clio_payments_transaction"
    CONTACT_INFORMATION = "contact_information"
    DISBURSEMENT_PAYMENT = "disbursement_payment"
    FEE_ALLOCATION = "fee_allocation"
    GENERAL_LEDGER = "general_ledger"
    GRANT_MATTERS = "grant_matters"
    INVOICE_PAYMENTS_V2 = "invoice_payments_v2"
    LAW_SOCIETY_OF_ALBERTA = "law_society_of_alberta"
    LAW_SOCIETY_OF_ALBERTA_AL = "law_society_of_alberta_al"
    LAW_SOCIETY_OF_ALBERTA_BAR = "law_society_of_alberta_bar"
    LAW_SOCIETY_OF_ALBERTA_TL = "law_society_of_alberta_tl"
    LAW_SOCIETY_OF_ALBERTA_TT = "law_society_of_alberta_tt"
    MATTER = "matter"
    MATTERS_BY_RESPONSIBLE_ATTORNEY = "matters_by_responsible_attorney"
    MATTER_BALANCE_SUMMARY = "matter_balance_summary"
    MATTER_PRODUCTIVITY_BY_USER = "matter_productivity_by_user"
    ORIGINATING_ATTORNEY_REVENUE = "originating_attorney_revenue"
    OTHER_REVENUE = "other_revenue"
    PRODUCTIVITY_BY_CLIENT = "productivity_by_client"
    PRODUCTIVITY_BY_USER = "productivity_by_user"
    REVENUE = "revenue"
    TASK_PRODUCTIVITY_BY_USER = "task_productivity_by_user"
    TASK_PROGRESS_BY_USER = "task_progress_by_user"
    TRUST_LEDGER = "trust_ledger"
    TRUST_LEDGER_NSW = "trust_ledger_nsw"
    TRUST_LISTING = "trust_listing"
    TRUST_MANAGEMENT = "trust_management"
    WORK_IN_PROGRESS = "work_in_progress"

    def __str__(self) -> str:
        return str(self.value)
