# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Source(Enum):
    """
    The source that visible applies to, by default the Clio Web UI (Expects 'mobile' or 'web').
    """
