# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class ParentType(Enum):
    """
    Type of object the *CustomFieldSet* is for.
    """
