# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type24(Enum):
    """
    The type of the Participant. Person and Company are subtypes of Contact
    """
