# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type21(Enum):
    """
    The type of the *MatterCustomRate*
    """
