# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type23(Enum):
    """
    Human readable description of the type of notification
    """
