# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type11(Enum):
    """
    The type of *Discount* being applied in your *Discount* rate.
    """
