# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type15(Enum):
    """
    Type of *Interest%* being applied
    """
