# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Type3(Enum):
    """
    The type of Balance this data is for.
    """
