# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Name1(Enum):
    """
    The type of *InstantMessenger* it is
    """
