# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Model(Enum):
    """
    What kind of records the webhook is for
    """
