# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class AccountBalanceBase(BaseModel):
    balance: Optional[float] = Field(
        None,
        description="The current balance of the bank account available to the matter or contact",
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *AccountBalance*"
    )
    name: Optional[str] = Field(None, description="The name of the bank account")
    type: Optional[str] = Field(
        None, description="The bank account type. Either Operating or Trust"
    )
