# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class ActivityCalendarEntryBase(BaseModel):
    calendar_owner_id: Optional[int] = Field(
        None, description="The id of the calendar owner."
    )
    etag: Optional[str] = Field(None, description="ETag for the *CalendarEntry*")
    id: Optional[str] = Field(
        None, description="Unique identifier for the *CalendarEntry*"
    )
