# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.activityratebase import ActivityRateBase


class ActivityRate(ActivityRateBase):
    group: Optional[GroupBase] = None
    user: Optional[UserBase] = None
