# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class ActivityDescriptionBase(BaseModel):
    accessible_to_user: Optional[bool] = Field(
        None, description="Determines if activity description is accessible to user"
    )
    category_type: Optional[str] = Field(
        None, description="Activity category rate type. Either hourly or flat fee"
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *ActivityDescription* was created (as a ISO-8601 timestamp)",
    )
    default: Optional[bool] = Field(
        None, description="Whether it is the user's default activity description"
    )
    etag: Optional[str] = Field(None, description="ETag for the *ActivityDescription*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *ActivityDescription*"
    )
    name: Optional[str] = Field(
        None, description="The name of the *ActivityDescription*"
    )
    type: Optional[str] = Field(
        None, description="The type of the *ActivityDescription*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *ActivityDescription* was last updated (as a ISO-8601 timestamp)",
    )
    utbms_activity_id: Optional[int] = Field(
        None,
        description="The UTBMS activity id if the *ActivityDescription* is a UTBMS activity description",
    )
    utbms_task_id: Optional[int] = Field(
        None,
        description="The UTBMS activity task id if attached to a UTBMS activity description",
    )
    utbms_task_name: Optional[str] = Field(
        None,
        description="The UTBMS activity task name if attached to a UTBMS activity description",
    )
    visible_to_co_counsel: Optional[bool] = Field(
        None,
        description="A toggle that determines if a co-counsel user of the firm can have access to this activity description",
    )
    xero_service_code: Optional[str] = Field(
        None, description="Custom Xero service code for this activity description"
    )
