# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ActivityTaskBase(BaseModel):
    etag: Optional[str] = Field(None, description="ETag for the *Task*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Task*")
