# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from clio_clients.models.activitydescriptionbase import ActivityDescriptionBase

class ActivityDescription(ActivityDescriptionBase):
    groups: Optional[List[GroupBase]] = Field(None, description="Group")
    rate: Optional[ActivityDescriptionRateBase] = None
    utbms_activity: Optional[UtbmsCodeBase] = None
    utbms_task: Optional[UtbmsCodeBase] = None
