# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.activitybase import ActivityBase
from clio_clients.models.activityshow import ActivityShow


class Activity(ActivityBase, ActivityShow):
    pass
