# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ActivityRateBase(BaseModel):
    co_counsel_contact_id: Optional[int] = Field(
        None, description="Filter ActivityRate records for the co-counsel."
    )
    contact_id: Optional[int] = Field(
        None, description="Filter ActivityRate records for the contact."
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *ActivityRate* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *ActivityRate*")
    flat_rate: Optional[bool] = Field(None, description="Whether this is a flat rate")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *ActivityRate*"
    )
    rate: Optional[float] = Field(
        None,
        description="Monetary value of this rate. Either hourly value or flat rate value",
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *ActivityRate* was last updated (as a ISO-8601 timestamp)",
    )
