# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.activitydescriptionbase import ActivityDescriptionBase
from pydantic import Field
from clio_clients.models.groupbase import GroupBase
from clio_clients.models.activitydescriptionratebase import ActivityDescriptionRateBase
from clio_clients.models.utbmscodebase import UtbmsCodeBase
from clio_clients.models.utbmscodebase import UtbmsCodeBase


class ActivityDescription(ActivityDescriptionBase):
    groups: Optional[List[GroupBase]] = Field(None, description="Group")
    rate: Optional[ActivityDescriptionRateBase] = None
    utbms_activity: Optional[UtbmsCodeBase] = None
    utbms_task: Optional[UtbmsCodeBase] = None
