# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.allocation import Allocation


class AllocationList(BaseModel):
    data: List[Allocation] = Field(..., description="Allocation List Response")
