# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .allocationbase import AllocationBase

class Allocation(AllocationBase):
    bill: Optional[BillBase] = None
    contact: Optional[ContactBase] = None
    destination_bank_account: Optional[BankAccountBase] = None
    matter: Optional[MatterBase] = None
    parent: Optional[PolymorphicObjectBase] = None
    source_bank_account: Optional[BankAccountBase] = None
