# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.allocationbase import AllocationBase
from clio_clients.models.billbase import BillBase
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.bankaccountbase import BankAccountBase
from clio_clients.models.matterbase import MatterBase
from clio_clients.models.polymorphicobjectbase import PolymorphicObjectBase
from clio_clients.models.bankaccountbase import BankAccountBase


class Allocation(AllocationBase):
    bill: Optional[BillBase] = None
    contact: Optional[ContactBase] = None
    destination_bank_account: Optional[BankAccountBase] = None
    matter: Optional[MatterBase] = None
    parent: Optional[PolymorphicObjectBase] = None
    source_bank_account: Optional[BankAccountBase] = None
