# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class AvatarBase(BaseModel):
    field_destroy: Optional[bool] = Field(
        None, alias="_destroy", description="Whether to destroy the *Avatar*"
    )
    created_at: Optional[str] = Field(
        None, description="The time the *Avatar* was created (as a ISO-8601 timestamp)"
    )
    etag: Optional[str] = Field(None, description="ETag for the *Avatar*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Avatar*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Avatar* was last updated (as a ISO-8601 timestamp)",
    )
    url: Optional[str] = Field(None, description="The URL for the *Avatar*")
