# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class BalanceBase(BaseModel):
    amount: Optional[float] = Field(None, description="The amount for this Balance.")
    due: Optional[float] = Field(
        None,
        description="The amount due for this Balance, factoring in applicable discounts.",
    )
    id: Optional[int] = Field(None, description="Unique identifier for the *Balance*")
    interest_amount: Optional[float] = Field(
        None, description="The interest amount for this Balance."
    )
    type: Optional[Type3] = Field(
        None, description="The type of Balance this data is for."
    )
