# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class BankTransactionBase(BaseModel):
    amount: Optional[float] = Field(None, description="The amount of the transaction.")
    bank_account_id: Optional[int] = Field(
        None, description="The associated bank account."
    )
    clio_payments_transaction: Optional[bool] = Field(
        None, description="Whether the transaction was created through online payments."
    )
    confirmation: Optional[str] = Field(
        None, description="The reference code for the transaction."
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *BankTransaction* was created (as a ISO-8601 timestamp)",
    )
    currency: Optional[str] = Field(
        None, description="The currency of the transaction."
    )
    current_account_balance: Optional[float] = Field(
        None, description="The current account balance."
    )
    date: Optional[str] = Field(None, description="The date of the transaction.")
    description: Optional[str] = Field(
        None, description="The description of the transaction."
    )
    etag: Optional[str] = Field(None, description="ETag for the *BankTransaction*")
    exchange_rate: Optional[float] = Field(
        None, description="The exchange rate of the transaction."
    )
    funds_in: Optional[float] = Field(
        None, description="The amount of funds received in this transaction."
    )
    funds_out: Optional[float] = Field(
        None, description="The amount of funds withdrawn in this transaction."
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *BankTransaction*"
    )
    read_only_confirmation: Optional[bool] = Field(
        None, description="Whether the transaction's reference code is read-only."
    )
    source: Optional[str] = Field(None, description="Where the transaction came from.")
    transaction_type: Optional[str] = Field(
        None, description="What kind of transaction."
    )
    type: Optional[str] = Field(None, description="The type of the *BankTransaction*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *BankTransaction* was last updated (as a ISO-8601 timestamp)",
    )
