# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.bankaccountbase import BankAccountBase
from clio_clients.models.userbase import UserBase


class BankAccount(BankAccountBase):
    user: Optional[UserBase] = None
