# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.banktransactionbase import BankTransactionBase


class BankTransaction(BankTransactionBase):
    allocation: Optional[AllocationBase] = None
    bank_account: Optional[BankAccountBase] = None
    bill: Optional[BillBase] = None
    client: Optional[ContactBase] = None
    matter: Optional[MatterBase] = None
