# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class BankTransferBase(BaseModel):
    amount: Optional[float] = Field(None, description="The amount of the transfer.")
    created_at: Optional[str] = Field(
        None,
        description="The time the *BankTransfer* was created (as a ISO-8601 timestamp)",
    )
    date: Optional[str] = Field(None, description="The date of the transfer.")
    description: Optional[str] = Field(
        None, description="The description of the transfer."
    )
    etag: Optional[str] = Field(None, description="ETag for the *BankTransfer*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *BankTransfer*"
    )
    primary_authorizer: Optional[str] = Field(
        None, description="The primary authorizer of the transfer."
    )
    secondary_authorizer: Optional[str] = Field(
        None, description="The secondary authorizer of the transfer."
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *BankTransfer* was last updated (as a ISO-8601 timestamp)",
    )
