# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .banktransferbase import BankTransferBase

class BankTransfer(BankTransferBase):
    client: Optional[ContactBase] = None
    destination_account: Optional[BankAccountBase] = None
    matter: Optional[MatterBase] = None
    source_account: Optional[BankAccountBase] = None
