# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.banktransactionbase import BankTransactionBase
from clio_clients.models.allocationbase import AllocationBase
from clio_clients.models.bankaccountbase import BankAccountBase
from clio_clients.models.billbase import BillBase
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.matterbase import MatterBase


class BankTransaction(BankTransactionBase):
    allocation: Optional[AllocationBase] = None
    bank_account: Optional[BankAccountBase] = None
    bill: Optional[BillBase] = None
    client: Optional[ContactBase] = None
    matter: Optional[MatterBase] = None
