# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.billableclientbase import BillableClientBase
from pydantic import Field
from clio_clients.models.billablematterbase import BillableMatterBase


class BillableClient(BillableClientBase):
    billable_matters: Optional[List[BillableMatterBase]] = Field(
        None, description="BillableMatter"
    )
