# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class BillThemeBase(BaseModel):
    account_id: Optional[int] = Field(
        None, description="The account number the *BillTheme* belongs to"
    )
    config: Optional[str] = Field(
        None, description="The configuration of the *BillTheme*"
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *BillTheme* was created (as a ISO-8601 timestamp)",
    )
    default: Optional[bool] = Field(
        None, description="Whether the *BillTheme* is the default for its account"
    )
    etag: Optional[str] = Field(None, description="ETag for the *BillTheme*")
    id: Optional[int] = Field(None, description="Unique identifier for the *BillTheme*")
    name: Optional[str] = Field(None, description="The name of the *BillTheme*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *BillTheme* was last updated (as a ISO-8601 timestamp)",
    )
