# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class BillableMatterBase(BaseModel):
    amount_in_trust: Optional[float] = Field(
        None, description="The trust amount available for the matter"
    )
    display_number: Optional[str] = Field(
        None, description="The reference to the matter"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *BillableMatter*"
    )
    unbilled_amount: Optional[float] = Field(
        None, description="The unbilled amount for the matter"
    )
    unbilled_hours: Optional[float] = Field(
        None, description="The unbilled number of hours for the matter"
    )
