# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.billablematter import BillableMatter


class BillableMatterList(BaseModel):
    data: List[BillableMatter] = Field(..., description="BillableMatter List Response")
