# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.billablematterbase import BillableMatterBase
from clio_clients.models.contactbase import ContactBase


class BillableMatter(BillableMatterBase):
    client: Optional[ContactBase] = None
