# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .billbase import BillBase

class Bill(BillBase):
    balances: Optional[List[BalanceBase]] = Field(None, description="Balance")
    bill_theme: Optional[BillThemeBase] = None
    billing_setting: Optional[BillingSettingBase] = None
    client: Optional[ContactBase] = None
    client_addresses: Optional[List[AddressBase]] = Field(None, description="Address")
    currency: Optional[CurrencyBase] = None
    destination_account: Optional[BankAccountBase] = None
    discount: Optional[DiscountBase] = None
    group: Optional[GroupBase] = None
    interest: Optional[InterestBase] = None
    legal_aid_uk_bill: Optional[LegalAidUkBillBase] = None
    matter_totals: Optional[List[MatterBalanceBase]] = Field(
        None, description="MatterBalance"
    )
    matters: Optional[List[MatterBase]] = Field(None, description="Matter")
    original_bill: Optional[BillBase] = None
    user: Optional[UserBase] = None
