# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.calendarentrybase import CalendarEntryBase
from pydantic import Field


class CalendarEntry(CalendarEntryBase):
    attendees: Optional[List[AttendeeBase]] = Field(None, description="Attendee")
    calendar_entry_event_type: Optional[CalendarEntryEventTypeBase] = None
    calendar_owner: Optional[CalendarBase] = None
    calendars: Optional[List[CalendarBase]] = Field(None, description="Calendar")
    conference_meeting: Optional[ConferenceMeetingBase] = None
    external_properties: Optional[List[ExternalPropertyBase]] = Field(
        None, description="ExternalProperty"
    )
    matter: Optional[MatterBase] = None
    matter_docket: Optional[MatterDocketBase] = None
    parent_calendar_entry: Optional[CalendarEntryBase] = None
    reminders: Optional[List[ReminderBase]] = Field(None, description="Reminder")
    time_entries: Optional[List[ActivityBase]] = Field(None, description="Activity")
