# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.color.color import Color


class CalendarEntryEventTypeBase(BaseModel):
    color: Optional[Color] = Field(
        None, description="The color describing the *CalendarEntryEventType*"
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *CalendarEntryEventType* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *CalendarEntryEventType*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *CalendarEntryEventType*"
    )
    name: Optional[str] = Field(
        None, description="The name for the *CalendarEntryEventType*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *CalendarEntryEventType* was last updated (as a ISO-8601 timestamp)",
    )
