# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.color.color1 import Color1
from clio_clients.models.lightcolor.lightcolor import LightColor


class CalendarVisibilityBase(BaseModel):
    color: Optional[Color1] = Field(None, description="Calendar color")
    created_at: Optional[str] = Field(
        None,
        description="The time the *CalendarVisibility* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *CalendarVisibility*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *CalendarVisibility*"
    )
    light_color: Optional[LightColor] = Field(
        None, description="Accent color to complement the main calendar color."
    )
    name: Optional[str] = Field(None, description="Calendar name")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *CalendarVisibility* was last updated (as a ISO-8601 timestamp)",
    )
    visible: Optional[bool] = Field(
        None,
        description="Whether the *CalendarVisibility* will be shown by default in the Clio Web UI.",
    )
