# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class CascadingTaskTemplateBase(BaseModel):
    id: Optional[int] = Field(
        None, description="Unique identifier for the *TaskTemplate*"
    )
    name: Optional[str] = Field(None, description="The name of the *TaskTemplate*")
