# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Category1(Enum):
    """
    The category of the report the preset generates
    """
