# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Category(Enum):
    """
    The practice area category associated with the *PracticeArea*
    """
