# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.clientbase import ClientBase
from clio_clients.models.clientshow import ClientShow


class Client(ClientBase, ClientShow):
    pass
