# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.cliopaymentspaymentbase import ClioPaymentsPaymentBase
from pydantic import Field
from clio_clients.models.allocationbase import AllocationBase
from clio_clients.models.banktransactionbase import BankTransactionBase
from clio_clients.models.billbase import BillBase
from clio_clients.models.cliopaymentslinkbase import ClioPaymentsLinkBase
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.bankaccountbase import BankAccountBase
from clio_clients.models.matterbase import MatterBase
from clio_clients.models.userbase import UserBase


class ClioPaymentsPayment(ClioPaymentsPaymentBase):
    allocations: Optional[List[AllocationBase]] = Field(None, description="Allocation")
    bank_transaction: Optional[BankTransactionBase] = None
    bills: Optional[List[BillBase]] = Field(None, description="Bill")
    clio_payments_link: Optional[ClioPaymentsLinkBase] = None
    contact: Optional[ContactBase] = None
    destination_account: Optional[BankAccountBase] = None
    matters: Optional[List[MatterBase]] = Field(None, description="Matter")
    user: Optional[UserBase] = None
