# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ClioCreatorBase(BaseModel):
    account_owner: Optional[bool] = Field(
        None, description="Whether the *ClioCreator* is the owner of the account"
    )
    clio_connect: Optional[bool] = Field(
        None, description="Whether the *ClioCreator* is a Clio Connect user"
    )
    court_rules_default_attendee: Optional[bool] = Field(
        None,
        description="Whether the *ClioCreator* is a default attendee for court rules events",
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *ClioCreator* was created (as a ISO-8601 timestamp)",
    )
    default_calendar_id: Optional[int] = Field(
        None, description="Default calendar id for *ClioCreator*."
    )
    email: Optional[str] = Field(None, description="The email of the *ClioCreator*")
    enabled: Optional[bool] = Field(
        None, description="Whether the *ClioCreator* is allowed to log in"
    )
    etag: Optional[str] = Field(None, description="ETag for the *ClioCreator*")
    first_name: Optional[str] = Field(
        None, description="The first name of the *ClioCreator*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *ClioCreator*"
    )
    initials: Optional[str] = Field(
        None, description="The initials of the *ClioCreator*"
    )
    last_name: Optional[str] = Field(
        None, description="The last name of the *ClioCreator*"
    )
    name: Optional[str] = Field(None, description="The full name of the *ClioCreator*")
    phone_number: Optional[str] = Field(
        None, description="The primary phone number for the *ClioCreator*."
    )
    rate: Optional[float] = Field(
        None, description="Default user activity rate for *ClioCreator*."
    )
    roles: Optional[List[str]] = Field(
        None, description="An array of roles assigned to this *ClioCreator*"
    )
    subscription_type: Optional[SubscriptionType] = Field(
        None, description="The subscription type of the *ClioCreator*"
    )
    time_zone: Optional[str] = Field(
        None, description="The selected time zone of the *ClioCreator*"
    )
    type: Optional[Type8] = Field(None, description="The type of the *ClioCreator*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *ClioCreator* was last updated (as a ISO-8601 timestamp)",
    )
