# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.cliopaymentslinkbase import ClioPaymentsLinkBase


class ClioPaymentsLink(ClioPaymentsLinkBase):
    bank_account: Optional[BankAccountBase] = None
    bill: Optional[BillBase] = None
    clio_payments_payment: Optional[ClioPaymentsPaymentBase] = None
    contact: Optional[ContactBase] = None
    destination_account: Optional[BankAccountBase] = None
    destination_contact: Optional[ContactBase] = None
