# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.cliopaymentspaymentbase import ClioPaymentsPaymentBase
from pydantic import Field


class ClioPaymentsPayment(ClioPaymentsPaymentBase):
    allocations: Optional[List[AllocationBase]] = Field(None, description="Allocation")
    bank_transaction: Optional[BankTransactionBase] = None
    bills: Optional[List[BillBase]] = Field(None, description="Bill")
    clio_payments_link: Optional[ClioPaymentsLinkBase] = None
    contact: Optional[ContactBase] = None
    destination_account: Optional[BankAccountBase] = None
    matters: Optional[List[MatterBase]] = Field(None, description="Matter")
    user: Optional[UserBase] = None
