# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .cliopaymentspaymentbase import ClioPaymentsPaymentBase

class ClioPaymentsPayment(ClioPaymentsPaymentBase):
    allocations: Optional[List[AllocationBase]] = Field(None, description="Allocation")
    bank_transaction: Optional[BankTransactionBase] = None
    bills: Optional[List[BillBase]] = Field(None, description="Bill")
    clio_payments_link: Optional[ClioPaymentsLinkBase] = None
    contact: Optional[ContactBase] = None
    destination_account: Optional[BankAccountBase] = None
    matters: Optional[List[MatterBase]] = Field(None, description="Matter")
    user: Optional[UserBase] = None
