# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.communication import Communication


class CommunicationList(BaseModel):
    data: List[Communication] = Field(..., description="Communication List Response")
