# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from clio_clients.models.communicationbase import CommunicationBase

class Communication(CommunicationBase):
    communication_eml_file: Optional[CommunicationEmlFileBase] = None
    documents: Optional[List[DocumentBase]] = Field(None, description="Document")
    external_properties: Optional[List[ExternalPropertyBase]] = Field(
        None, description="ExternalProperty"
    )
    matter: Optional[MatterBase] = None
    notification_event_subscribers: Optional[List[NotificationEventSubscriberBase]] = (
        Field(None, description="NotificationEventSubscriber")
    )
    receivers: Optional[List[Participant]] = Field(None, description="Participant")
    senders: Optional[List[Participant]] = Field(None, description="Participant")
    time_entries: Optional[List[ActivityBase]] = Field(None, description="Activity")
    user: Optional[UserBase] = None
