# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.commentbase import CommentBase


class Comment(CommentBase):
    creator: Optional[UserBase] = None
    document_version: Optional[DocumentVersionBase] = None
