# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class CommentBase(BaseModel):
    created_at: Optional[str] = Field(
        None, description="The time the *Comment* was created (as a ISO-8601 timestamp)"
    )
    etag: Optional[str] = Field(None, description="ETag for the *Comment*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Comment*")
    message: Optional[str] = Field(None, description="The content of the Comment")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Comment* was last updated (as a ISO-8601 timestamp)",
    )
