# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.comment import Comment


class CommentList(BaseModel):
    data: List[Comment] = Field(..., description="Comment List Response")
