# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:  # pragma: no cover - used for type checkers only
    from .contact import Contact


class ContactShow(BaseModel):
    """Response wrapper containing a Contact."""

    data: "Contact" = Field(..., description="Contact")
