# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ContingencyFeeBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *ContingencyFee* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *ContingencyFee*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *ContingencyFee*"
    )
    show_contingency_award: Optional[bool] = Field(
        None, description="Whether the *ContingencyFee* is posted or on a bill"
    )
    ed_at: Optional[str] = Field(
        None,
        description="The time the *ContingencyFee* was last updated (as a ISO-8601 timestamp)",
    )
