# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from clio_clients.models.contact import Contact
from pydantic import BaseModel, Field


class ContactList(BaseModel):
    data: List[Contact] = Field(..., description="Contact List Response")
