# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.conversationmessage import ConversationMessage


class ConversationMessageShow(BaseModel):
    data: ConversationMessage
