# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.conversationmessagebase import ConversationMessageBase
from pydantic import Field


class ConversationMessage(ConversationMessageBase):
    conversation: Optional[ConversationBase] = None
    document: Optional[DocumentBase] = None
    receivers: Optional[List[UnredactedParticipantBase]] = Field(
        None, description="UnredactedParticipant"
    )
    sender: Optional[UnredactedParticipantBase] = None
