# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.conversationbase import ConversationBase
from pydantic import Field


class Conversation(ConversationBase):
    documents: Optional[List[DocumentBase]] = Field(None, description="Document")
    first_message: Optional[ConversationMessageBase] = None
    last_message: Optional[ConversationMessageBase] = None
    matter: Optional[MatterBase] = None
    memberships: Optional[List[ConversationMembership]] = Field(
        None, description="ConversationMembership"
    )
    messages: Optional[List[ConversationMessageBase]] = Field(
        None, description="ConversationMessage"
    )
