# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.conversationmessage import ConversationMessage


class ConversationMessageList(BaseModel):
    data: List[ConversationMessage] = Field(
        ..., description="ConversationMessage List Response"
    )
