# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from clio_clients.models.conversationbase import ConversationBase

class Conversation(ConversationBase):
    documents: Optional[List[DocumentBase]] = Field(None, description="Document")
    first_message: Optional[ConversationMessageBase] = None
    last_message: Optional[ConversationMessageBase] = None
    matter: Optional[MatterBase] = None
    memberships: Optional[List[ConversationMembership]] = Field(
        None, description="ConversationMembership"
    )
    messages: Optional[List[ConversationMessageBase]] = Field(
        None, description="ConversationMessage"
    )
