# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.conversationmembershipbase import ConversationMembershipBase


class ConversationMembership(ConversationMembershipBase):
    member: Optional[UnredactedParticipantBase] = None
