# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class ConversationMembershipBase(BaseModel):
    archived: Optional[bool] = Field(
        None,
        description="Whether or not the ConversationMembership has been archived by the member",
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *ConversationMembership* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *ConversationMembership*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *ConversationMembership*"
    )
    read: Optional[bool] = Field(
        None,
        description="Whether or not the ConversationMembership has been read by the member",
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *ConversationMembership* was last updated (as a ISO-8601 timestamp)",
    )
