# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.creditmemo import CreditMemo


class CreditMemoList(BaseModel):
    data: List[CreditMemo] = Field(..., description="CreditMemo List Response")
