# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.creditmemobase import CreditMemoBase
from pydantic import Field


class CreditMemo(CreditMemoBase):
    allocations: Optional[List[AllocationBase]] = Field(None, description="Allocation")
    contact: Optional[ContactBase] = None
    user: Optional[UserBase] = None
