# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.currency import Currency


class CurrencyList(BaseModel):
    data: List[Currency] = Field(..., description="Currency List Response")
