# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class CurrencyBase(BaseModel):
    code: Optional[str] = Field(None, description="ISO 4217 code for the *Currency*")
    created_at: Optional[str] = Field(
        None,
        description="The time the *Currency* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *Currency*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Currency*")
    sign: Optional[str] = Field(
        None, description="Symbol used to denote monetary values using this *Currency*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Currency* was last updated (as a ISO-8601 timestamp)",
    )
