# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.customfield import CustomField
from clio_clients.models.customfieldvaluebase import CustomFieldValueBase
from clio_clients.models.picklistoption import PicklistOption
from clio_clients.models.matter import Matter
from clio_clients.models.contact import Contact


class CustomFieldValue(CustomFieldValueBase):
    """Full representation of a custom field value."""

    custom_field: Optional[CustomField] = None
    picklist_option: Optional[PicklistOption] = None
    matter: Optional[Matter] = None
    contact: Optional[Contact] = None


CustomFieldValue.update_forward_refs()
