# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.customaction import CustomAction


class CustomActionList(BaseModel):
    data: List[CustomAction] = Field(..., description="CustomAction List Response")
