# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class CustomFieldBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *CustomField* was created (as a ISO-8601 timestamp)",
    )
    deleted: Optional[bool] = Field(
        None, description="Whether the *CustomField* is deleted for future use"
    )
    display_order: Optional[int] = Field(
        None, description="The display position of the *CustomField*"
    )
    displayed: Optional[bool] = Field(
        None, description="Whether the *CustomField* is displayed by default"
    )
    etag: Optional[str] = Field(None, description="ETag for the *CustomField*")
    field_type: Optional[FieldType1] = Field(
        None, description="Field type of the *CustomField*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *CustomField*"
    )
    name: Optional[str] = Field(None, description="The name of the *CustomField*")
    parent_type: Optional[ParentType1] = Field(
        None, description="Type of object the *CustomField* is for"
    )
    required: Optional[bool] = Field(
        None, description="Whether the *CustomField* requires a value"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *CustomField* was last updated (as a ISO-8601 timestamp)",
    )
