# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.customfieldsetbase import CustomFieldSetBase
from pydantic import Field


class CustomFieldSet(CustomFieldSetBase):
    custom_fields: Optional[List[CustomFieldBase]] = Field(
        None, description="CustomField"
    )
