# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.customfieldset import CustomFieldSet


class CustomFieldSetList(BaseModel):
    data: List[CustomFieldSet] = Field(..., description="CustomFieldSet List Response")
