# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.customfieldbase import CustomFieldBase


class CustomFieldExtended(CustomFieldBase):
    picklist_options: Optional[List[PicklistOption]] = None
