# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .customfieldvaluebase import CustomFieldValueBase

class CustomFieldValueExtended(CustomFieldValueBase):
    custom_field: Optional[CustomField] = None
    picklist_option: Optional[PicklistOption] = None
    matter: Optional[Matter] = None
    contact: Optional[Contact] = None
