# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.damage import Damage


class DamageList(BaseModel):
    data: List[Damage] = Field(..., description="Damage List Response")
