# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class DamageBase(BaseModel):
    amount: Optional[float] = Field(None, description="Amount for Damage")
    created_at: Optional[str] = Field(
        None, description="The time the *Damage* was created (as a ISO-8601 timestamp)"
    )
    damage_type: Optional[DamageType] = Field(
        None, description="Damage type of the record"
    )
    description: Optional[str] = Field(None, description="Description for Damage")
    etag: Optional[str] = Field(None, description="ETag for the *Damage*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Damage*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Damage* was last updated (as a ISO-8601 timestamp)",
    )
