# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.contactbase import ContactBase
from clio_clients.models.instantmessengerbase import InstantMessengerBase


class Data(ContactBase, InstantMessengerBase):
    pass
