# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.documentbase import DocumentBase
from clio_clients.models.documentshow import DocumentShow


class Document(DocumentBase, DocumentShow):
    pass
