# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.documentautomation import DocumentAutomation


class DocumentAutomationList(BaseModel):
    data: List[DocumentAutomation] = Field(
        ..., description="DocumentAutomation List Response"
    )
