# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.documentcategory import DocumentCategory


class DocumentCategoryList(BaseModel):
    data: List[DocumentCategory] = Field(
        ..., description="DocumentCategory List Response"
    )
