# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.state2 import State2


class DocumentArchiveBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *DocumentArchive* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *DocumentArchive*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *DocumentArchive*"
    )
    message: Optional[str] = Field(
        None,
        description="A message to indicate why the DocumentArchive didn't complete.",
    )
    progress: Optional[float] = Field(
        None, description="The percent completion of the DocumentArchive."
    )
    size: Optional[int] = Field(
        None, description="The size of the DocumentArchive in bytes."
    )
    state: Optional[State2] = Field(
        None, description="The current state of the DocumentArchive."
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *DocumentArchive* was last updated (as a ISO-8601 timestamp)",
    )
