# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class DocumentCategoryBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *DocumentCategory* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *DocumentCategory*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *DocumentCategory*"
    )
    name: Optional[str] = Field(None, description="The name of the *DocumentCategory*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *DocumentCategory* was last updated (as a ISO-8601 timestamp)",
    )
