# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.documentversion import DocumentVersion


class DocumentVersionList(BaseModel):
    data: List[DocumentVersion] = Field(
        ..., description="DocumentVersion List Response"
    )
