# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class DocumentAutomationBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *DocumentAutomation* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *DocumentAutomation*")
    export_formats: Optional[ExportFormats] = Field(
        None, description="An array of what formats were requested"
    )
    filename: Optional[str] = Field(
        None, description="The name of the file being generated."
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *DocumentAutomation*"
    )
    state: Optional[State3] = Field(
        None, description="A text description of what the automation is currently doing"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *DocumentAutomation* was last updated (as a ISO-8601 timestamp)",
    )
