# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.documentarchivebase import DocumentArchiveBase


class DocumentArchive(DocumentArchiveBase):
    pass
