# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class DocumentTemplateBase(BaseModel):
    content_type: Optional[str] = Field(
        None,
        description="A standard MIME type describing the format of the object data.",
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *DocumentTemplate* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *DocumentTemplate*")
    filename: Optional[str] = Field(
        None, description="The name of the original file that was uploaded"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *DocumentTemplate*"
    )
    size: Optional[int] = Field(None, description="The size in bytes of the template")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *DocumentTemplate* was last updated (as a ISO-8601 timestamp)",
    )
