# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class ErrorDetail(BaseModel):
    message: str = Field(..., description="Detailed message about the error")
    type: str = Field(..., description="Unique name for this error")
