# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class ErrorDetail(BaseModel):
    message: str = Field(..., description="Detailed message about the error")
    type: str = Field(..., description="Unique name for this error")
