# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class EvergreenRetainerBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *EvergreenRetainer* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *EvergreenRetainer*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *EvergreenRetainer*"
    )
    minimum_threshold: Optional[float] = Field(
        None,
        description="The trust balance threshold for the associated Matter. When the balance falls below the threshold, the retainer's associated recipients (firm users) will receive a notification.",
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *EvergreenRetainer* was last updated (as a ISO-8601 timestamp)",
    )
