# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.expensecategory import ExpenseCategory


class ExpenseCategoryShow(BaseModel):
    data: ExpenseCategory
