# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.expensecategorybase import ExpenseCategoryBase
from pydantic import Field
from clio_clients.models.groupbase import GroupBase
from clio_clients.models.utbmscodebase import UtbmsCodeBase


class ExpenseCategory(ExpenseCategoryBase):
    groups: Optional[List[GroupBase]] = Field(None, description="Group")
    utbms_code: Optional[UtbmsCodeBase] = None
