# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.expensecategory import ExpenseCategory


class ExpenseCategoryList(BaseModel):
    data: List[ExpenseCategory] = Field(
        ..., description="ExpenseCategory List Response"
    )
