# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class FolderList(BaseModel):
    data: List[Folder] = Field(..., description="Folder List Response")
