# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.grantfundingsourcebase import GrantFundingSourceBase
from pydantic import Field


class GrantFundingSource(GrantFundingSourceBase):
    grants: Optional[List[GrantBase]] = Field(None, description="Grant")
