# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class GrantBase(BaseModel):
    balance: Optional[str] = Field(None, description="Balance of the grant")
    created_at: Optional[str] = Field(
        None, description="The time the *Grant* was created (as a ISO-8601 timestamp)"
    )
    etag: Optional[str] = Field(None, description="ETag for the *Grant*")
    funding_code: Optional[str] = Field(None, description="Funding code of the grant")
    funding_code_and_name: Optional[str] = Field(
        None, description="Funding code and name of the grant"
    )
    funding_source_name: Optional[str] = Field(
        None, description="Name of the funding source of the grant"
    )
    id: Optional[int] = Field(None, description="Unique identifier for the *Grant*")
    name: Optional[str] = Field(None, description="The name of the *Grant*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Grant* was last updated (as a ISO-8601 timestamp)",
    )
