# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class GrantFundingSourceBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *GrantFundingSource* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *GrantFundingSource*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *GrantFundingSource*"
    )
    name: Optional[str] = Field(
        None, description="The name of the *GrantFundingSource*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *GrantFundingSource* was last updated (as a ISO-8601 timestamp)",
    )
