# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.grant import Grant


class GrantList(BaseModel):
    data: List[Grant] = Field(..., description="Grant List Response")
