# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.grantbase import GrantBase
from clio_clients.models.grantfundingsourcebase import GrantFundingSourceBase


class Grant(GrantBase):
    grant_funding_source: Optional[GrantFundingSourceBase] = None
