# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.group import Group


class GroupList(BaseModel):
    data: List[Group] = Field(..., description="Group List Response")
