# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.groupbase import GroupBase
from pydantic import Field
from clio_clients.models.userbase import UserBase


class Group(GroupBase):
    users: Optional[List[UserBase]] = Field(None, description="User")
