# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class InterestType(Enum):
    """
    The type of interest to be calculated for the *PaymentProfile (Simple or Compound)
    """
