# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.interestchargebase import InterestChargeBase
from pydantic import Field


class InterestCharge(InterestChargeBase):
    balances: Optional[List[BalanceBase]] = Field(None, description="Balance")
    bill: Optional[BillBase] = None
    matters: Optional[List[MatterBase]] = Field(None, description="Matter")
