# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .itembase import ItemBase

class Item(ItemBase):
    contact: Optional[ContactBase] = None
    creator: Optional[ClioCreatorBase] = None
    document_category: Optional[DocumentCategoryBase] = None
    external_properties: Optional[List[ExternalPropertyBase]] = Field(
        None, description="ExternalProperty"
    )
    group: Optional[GroupBase] = None
    latest_document_version: Optional[DocumentVersionBase] = None
    matter: Optional[MatterBase] = None
    parent: Optional[LinkedFolderBase] = None
