# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.itembase import ItemBase
from pydantic import Field
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.cliocreatorbase import ClioCreatorBase
from clio_clients.models.documentcategorybase import DocumentCategoryBase
from clio_clients.models.externalpropertybase import ExternalPropertyBase
from clio_clients.models.groupbase import GroupBase
from clio_clients.models.documentversionbase import DocumentVersionBase
from clio_clients.models.matterbase import MatterBase
from clio_clients.models.linkedfolderbase import LinkedFolderBase


class Item(ItemBase):
    contact: Optional[ContactBase] = None
    creator: Optional[ClioCreatorBase] = None
    document_category: Optional[DocumentCategoryBase] = None
    external_properties: Optional[List[ExternalPropertyBase]] = Field(
        None, description="ExternalProperty"
    )
    group: Optional[GroupBase] = None
    latest_document_version: Optional[DocumentVersionBase] = None
    matter: Optional[MatterBase] = None
    parent: Optional[LinkedFolderBase] = None
