# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.item import Item


class ItemList(BaseModel):
    data: List[Item] = Field(..., description="Item List Response")
