# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class JobTitleBase(BaseModel):
    etag: Optional[str] = Field(None, description="ETag for the *JobTitle*")
    id: Optional[int] = Field(None, description="Unique identifier for the *JobTitle*")
    initials: Optional[str] = Field(None, description="Initials of the job title")
    name: Optional[str] = Field(None, description="Name of the job title")
