# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.jurisdiction import Jurisdiction


class JurisdictionList(BaseModel):
    data: List[Jurisdiction] = Field(..., description="Jurisdiction List Response")
