# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JurisdictionBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *Jurisdiction* was created (as a ISO-8601 timestamp)",
    )
    default: Optional[bool] = Field(
        None, description="Whether the *Jurisdiction* is default for the current user"
    )
    description: Optional[str] = Field(None, description="Description")
    display_timezone: Optional[str] = Field(
        None, description="Formatted IANA timezone with UTC offset"
    )
    etag: Optional[str] = Field(None, description="ETag for the *Jurisdiction*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *Jurisdiction*"
    )
    is_local_timezone: Optional[bool] = Field(
        None,
        description="Boolean value for when the timezone is in the local users timezone",
    )
    system_id: Optional[int] = Field(None, description="Server ID")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Jurisdiction* was last updated (as a ISO-8601 timestamp)",
    )
    valid_subscription: Optional[bool] = Field(
        None, description="Boolean value for whether the user has the jurisdictions"
    )
