# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.jurisdictionbase import JurisdictionBase
from pydantic import Field


class Jurisdiction(JurisdictionBase):
    service_types: Optional[List[ServiceTypeBase]] = Field(
        None, description="ServiceType"
    )
