# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.laukcivilcontrolledrate import LaukCivilControlledRate


class LaukCivilControlledRateList(BaseModel):
    data: List[LaukCivilControlledRate] = Field(
        ..., description="LaukCivilControlledRate List Response"
    )
