# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.laukexpensecategory import LaukExpenseCategory


class LaukExpenseCategoryList(BaseModel):
    data: List[LaukExpenseCategory] = Field(
        ..., description="LaukExpenseCategory List Response"
    )
