# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field


class LaukCriminalControlledRateBase(BaseModel):
    activity: Optional[str] = Field(
        None, description="Activity of the *LaukCriminalControlledRate*"
    )
    activity_type: Optional[str] = Field(None, description="Activity type")
    category_of_law: Optional[str] = Field(None, description="Category of law")
    counsel: Optional[str] = Field(None, description="Associated counsel")
    court: Optional[str] = Field(None, description="Court associated")
    created_at: Optional[str] = Field(
        None,
        description="The time the *LaukCriminalControlledRate* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *LaukCriminalControlledRate*"
    )
    exceptional: Optional[Decimal] = Field(
        None, description="Fee applied for high activity count"
    )
    fee: Optional[Decimal] = Field(None, description="Fee amount")
    fee_scheme: Optional[str] = Field(None, description="Fee scheme")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *LaukCriminalControlledRate*"
    )
    key: Optional[str] = Field(None, description="Unique key")
    post_sept_22_exceptional: Optional[Decimal] = Field(
        None, description="Post-Sept 22 exceptional fee"
    )
    post_sept_22_fee: Optional[Decimal] = Field(
        None, description="Post-Sept 22 fee amount"
    )
    rate_type: Optional[str] = Field(None, description="Rate type")
    region: Optional[str] = Field(None, description="Region")
    solicitor_type: Optional[str] = Field(None, description="Solicitor type")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *LaukCriminalControlledRate* was last updated (as a ISO-8601 timestamp)",
    )
