# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class LegalAidUkBillBase(BaseModel):
    additional_travel_payment: Optional[bool] = Field(
        None, description="Additional travel payment, for Legal Aid England and Wales"
    )
    adjourned_hearing_fee: Optional[str] = Field(
        None, description="Adjourned hearing fee"
    )
    advice_time: Optional[int] = Field(None, description="Advice time")
    advocacy_costs: Optional[float] = Field(None, description="Advocacy costs")
    bill_type: Optional[int] = Field(None, description="Bill type")
    case_concluded: Optional[str] = Field(None, description="Case concluded")
    case_stage_level: Optional[int] = Field(None, description="Case stage level")
    cla_exemption_code: Optional[str] = Field(None, description="CLA exemption code")
    cla_reference: Optional[str] = Field(None, description="CLA reference")
    cmrh_oral: Optional[int] = Field(None, description="CMRH oral")
    cmrh_telephone: Optional[int] = Field(None, description="CMRH telephone")
    cost_of_counsel: Optional[str] = Field(None, description="Cost of counsel")
    costs_are_those_of: Optional[int] = Field(None, description="Costs are those of")
    court_location: Optional[str] = Field(
        None, description="Court location (HPCDS matters)"
    )
    date_of_claim: Optional[str] = Field(None, description="Date of claim")
    designated_accredited_representative: Optional[int] = Field(
        None, description="Designated accredited representative"
    )
    detention_travel_and_waiting_costs: Optional[str] = Field(
        None, description="Detention travel & waiting costs ex VAT"
    )
    disbursements_vat: Optional[float] = Field(None, description="Disbursements VAT")
    exceptional_case_funding_reference: Optional[str] = Field(
        None, description="Exceptional case funding reference"
    )
    exemption_criteria_satisfied: Optional[int] = Field(
        None, description="Exemption criteria satisfied"
    )
    follow_on_work: Optional[int] = Field(None, description="Follow on work")
    ho_interview: Optional[int] = Field(None, description="HO interview")
    ho_ucn: Optional[int] = Field(None, description="HO UCN")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *LegalAidUkBill*"
    )
    independent_medical_reports_claimed: Optional[str] = Field(
        None, description="Independent medical reports claimed"
    )
    jr_form_filling: Optional[str] = Field(
        None, description="JR/Form filling ex VAT, for Legal Aid England and Wales"
    )
    maat_id: Optional[str] = Field(None, description="MAAT ID")
    meetings_attended: Optional[int] = Field(None, description="Meetings attended")
    mht_ref_no: Optional[str] = Field(None, description="MHT reference number")
    net_disbursements: Optional[float] = Field(None, description="Net disbursements")
    net_profit_costs: Optional[float] = Field(None, description="Net profit cost")
    niat_disbursement_prior_authority_number: Optional[str] = Field(
        None, description="NIAT disbursement prior authority number"
    )
    number_of_attendances: Optional[int] = Field(
        None, description="Number of attendances"
    )
    outcome_for_the_client: Optional[int] = Field(
        None, description="Outcome for the client"
    )
    prior_authority_reference: Optional[str] = Field(
        None, description="Prior authority reference number"
    )
    profit_costs_ex_vat: Optional[int] = Field(None, description="Profit costs ex VAT")
    representation_order_date: Optional[str] = Field(
        None, description="Representation order date"
    )
    stage_reached: Optional[int] = Field(None, description="Stage reached")
    substantive_hearing: Optional[int] = Field(None, description="Substantive hearing")
    travel_and_waiting_costs: Optional[float] = Field(
        None, description="Travel & waiting costs"
    )
    travel_time: Optional[int] = Field(None, description="Travel time")
    value_of_costs: Optional[str] = Field(None, description="Value of costs")
    waiting_time: Optional[int] = Field(None, description="Waiting time")
