# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class LienBase(BaseModel):
    amount: Optional[float] = Field(None, description="The amount for Lien")
    created_at: Optional[str] = Field(
        None, description="The time the *Lien* was created (as a ISO-8601 timestamp)"
    )
    description: Optional[str] = Field(None, description="Lien description")
    etag: Optional[str] = Field(None, description="ETag for the *Lien*")
    id: Optional[int] = Field(None, description="Unique identifier for the *Lien*")
    lien_type: Optional[LienType] = Field(None, description="Lien type")
    mark_as_lien: Optional[bool] = Field(None, description="Mark item as Lien")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Lien* was last updated (as a ISO-8601 timestamp)",
    )
