# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.lineitembase import LineItemBase


class LineItem(LineItemBase):
    activity: Optional[ActivityBase] = None
    bill: Optional[BillBase] = None
    discount: Optional[DiscountBase] = None
    included_line_item_totals: Optional[LineItemTotalsBase] = None
    matter: Optional[MatterBase] = None
    user: Optional[UserBase] = None
