# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class LineItemTotalsBase(BaseModel):
    discount_percent: Optional[float] = Field(
        None, description="Sum of discount as percentage for included line items."
    )
    price: Optional[float] = Field(
        None, description="Sum of price for included line items."
    )
    quantity: Optional[float] = Field(
        None, description="Sum of quantity for included line items."
    )
    sub_total: Optional[float] = Field(
        None, description="Sum of total before discount and tax is applied."
    )
    total: Optional[float] = Field(
        None, description="Sum of total for included line items."
    )
