# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.lineitembase import LineItemBase
from clio_clients.models.activitybase import ActivityBase
from clio_clients.models.billbase import BillBase
from clio_clients.models.discountbase import DiscountBase
from clio_clients.models.lineitemtotalsbase import LineItemTotalsBase
from clio_clients.models.matterbase import MatterBase
from clio_clients.models.userbase import UserBase


class LineItem(LineItemBase):
    activity: Optional[ActivityBase] = None
    bill: Optional[BillBase] = None
    discount: Optional[DiscountBase] = None
    included_line_item_totals: Optional[LineItemTotalsBase] = None
    matter: Optional[MatterBase] = None
    user: Optional[UserBase] = None
