# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .matterdocketbase import MatterDocketBase

class MatterDocket(MatterDocketBase):
    calendar_entries: Optional[List[CalendarEntryBase]] = Field(
        None, description="CalendarEntry"
    )
    jurisdiction: Optional[JurisdictionBase] = None
    matter: Optional[MatterBase] = None
    service_type: Optional[ServiceTypeBase] = None
    trigger: Optional[JurisdictionsToTriggerBase] = None
