# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class MatterDocketBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *MatterDocket* was created (as a ISO-8601 timestamp)",
    )
    deleted_at: Optional[str] = Field(
        None,
        description="The time the *MatterDocket* was deleted (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *MatterDocket*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *MatterDocket*"
    )
    name: Optional[str] = Field(None, description="The name of the *MatterDocket*")
    start_date: Optional[str] = Field(
        None, description="The date the *MatterDocket* will start (as a ISO-8601 date)"
    )
    start_time: Optional[str] = Field(
        None,
        description="The time the *MatterDocket* will start, required for specific triggers (as a ISO-8601 timestamp)",
    )
    status: Optional[str] = Field(
        None, description="The status of the *MatterDocket* creation"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *MatterDocket* was last updated (as a ISO-8601 timestamp)",
    )
