# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.matterdocketbase import MatterDocketBase
from pydantic import Field


class MatterDocket(MatterDocketBase):
    calendar_entries: Optional[List[CalendarEntryBase]] = Field(
        None, description="CalendarEntry"
    )
    jurisdiction: Optional[JurisdictionBase] = None
    matter: Optional[MatterBase] = None
    service_type: Optional[ServiceTypeBase] = None
    trigger: Optional[JurisdictionsToTriggerBase] = None
