# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.type.type21 import Type21


class MatterCustomRateBase(BaseModel):
    on_invoice: Optional[bool] = Field(
        None,
        description="Specifies if the matter's associated activity is posted or on a bill.",
    )
    type: Optional[Type21] = Field(
        None, description="The type of the *MatterCustomRate*"
    )
