# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from clio_clients.models.event.event import Event
from clio_clients.models.payload import Payload


class MatterCreatedWebhookEvent(BaseModel):
    event: Optional[Event] = None
    payload: Optional[Payload] = None
    timestamp: Optional[str] = None
