# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.mattercontactsbase import MatterContactsBase
from pydantic import Field


class MatterContacts(MatterContactsBase):
    addresses: Optional[List[AddressBase]] = Field(None, description="Address")
    avatar: Optional[AvatarBase] = None
    company: Optional[ContactBase] = None
    custom_field_values: Optional[List[CustomFieldValueBase]] = Field(
        None, description="CustomFieldValue"
    )
    email_addresses: Optional[List[EmailAddressBase]] = Field(
        None, description="EmailAddress"
    )
    phone_numbers: Optional[List[PhoneNumberBase]] = Field(
        None, description="PhoneNumber"
    )
    primary_address: Optional[AddressBase] = None
    primary_web_site: Optional[WebSiteBase] = None
    relationship: Optional[RelationshipBase] = None
    secondary_address: Optional[AddressBase] = None
    secondary_web_site: Optional[WebSiteBase] = None
    web_sites: Optional[List[WebSiteBase]] = Field(None, description="WebSite")
