# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.matterdocket import MatterDocket  # Adjust the import path if needed
from pydantic import BaseModel


class MatterDocketShow(BaseModel):
    data: MatterDocket
