# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class MatterStageBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *MatterStage* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *MatterStage*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *MatterStage*"
    )
    name: Optional[str] = Field(None, description="The name of the *MatterStage*")
    order: Optional[int] = Field(
        None, description="The order of the matter stage within a practice area"
    )
    practice_area_id: Optional[str] = Field(None, description="Practice Area ID")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *MatterStage* was last updated (as a ISO-8601 timestamp)",
    )
