# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.matterbase import MatterBase
from clio_clients.models.mattershow import MatterShow


class Matter1(MatterBase, MatterShow):
    pass
