# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class MatterBalanceBase(BaseModel):
    amount: Optional[float] = Field(
        None, description="The amount of balance of a matter."
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *MatterBalance*"
    )
