# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.matterdocket import MatterDocket


class MatterDocketList(BaseModel):
    data: List[MatterDocket] = Field(..., description="MatterDocket List Response")
