# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.matterstage import MatterStage


class MatterStageList(BaseModel):
    data: List[MatterStage] = Field(..., description="MatterStage List Response")
