# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.mattercustomratebase import MatterCustomRateBase
from pydantic import Field


class MatterCustomRate(MatterCustomRateBase):
    rates: Optional[List[PolymorphicCustomRate]] = Field(
        None, description="PolymorphicCustomRate"
    )
