# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class MatterCustomRateBase(BaseModel):
    on_invoice: Optional[bool] = Field(
        None,
        description="Specifies if the matter's associated activity is posted or on a bill.",
    )
    type: Optional[Type21] = Field(
        None, description="The type of the *MatterCustomRate*"
    )
