# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class MatterList(BaseModel):
    data: List[Matter1] = Field(..., description="Matter List Response")
