# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.matterbillrecipientbase import MatterBillRecipientBase
from clio_clients.models.contactbase import ContactBase


class MatterBillRecipient(MatterBillRecipientBase):
    recipient: Optional[ContactBase] = None
