# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.medicalrecordsrequestbase import MedicalRecordsRequestBase
from pydantic import Field


class MedicalRecordsRequest(MedicalRecordsRequestBase):
    matter: Optional[MatterBase] = None
    medical_bills: Optional[List[MedicalBillBase]] = Field(
        None, description="MedicalBill"
    )
    medical_provider: Optional[ContactBase] = None
    medical_records: Optional[List[MedicalRecordBase]] = Field(
        None, description="MedicalRecord"
    )
