# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.medicalbillbase import MedicalBillBase
from pydantic import Field


class MedicalBill(MedicalBillBase):
    liens: Optional[List[LienBase]] = Field(None, description="Lien")
    matter: Optional[MatterBase] = None
