# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.billsstatus import BillsStatus
from clio_clients.models.recordsstatus import RecordsStatus


class MedicalRecordsRequestBase(BaseModel):
    bills_follow_up_date: Optional[str] = Field(
        None, description="Follow up date for Medical Bills (as a ISO-8601 date)"
    )
    bills_request_date: Optional[str] = Field(
        None,
        description="Date for when the Medical Bills were requested (as a ISO-8601 date)",
    )
    bills_status: Optional[BillsStatus] = Field(
        None, description="Medical Bills status"
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *MedicalRecordsRequest* was created (as a ISO-8601 timestamp)",
    )
    description: Optional[str] = Field(
        None, description="Description of the Medical Records Detail"
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *MedicalRecordsRequest*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *MedicalRecordsRequest*"
    )
    in_treatment: Optional[bool] = Field(
        None, description="Treatment status for Medical Records Detail"
    )
    records_follow_up_date: Optional[str] = Field(
        None, description="Follow up date for Medical Records (as a ISO-8601 date)"
    )
    records_request_date: Optional[str] = Field(
        None,
        description="Date for when the Medical Records were requested (as a ISO-8601 date)",
    )
    records_status: Optional[RecordsStatus] = Field(
        None, description="Medical Records status"
    )
    treatment_end_date: Optional[str] = Field(
        None,
        description="Treatment end date for Medical Records Detail (as a ISO-8601 date)",
    )
    treatment_start_date: Optional[str] = Field(
        None,
        description="Treatment start date for Medical Records Detail (as a ISO-8601 date)",
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *MedicalRecordsRequest* was last updated (as a ISO-8601 timestamp)",
    )
