# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from .medicalrecordsrequestbase import MedicalRecordsRequestBase

class MedicalRecordsRequest(MedicalRecordsRequestBase):
    matter: Optional[MatterBase] = None
    medical_bills: Optional[List[MedicalBillBase]] = Field(
        None, description="MedicalBill"
    )
    medical_provider: Optional[ContactBase] = None
    medical_records: Optional[List[MedicalRecordBase]] = Field(
        None, description="MedicalRecord"
    )
