# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class MultipartBase(BaseModel):
    part_number: Optional[int] = Field(
        None,
        description="Unique identifier of a part which defines its position within the document being uploaded.",
    )
    put_url: Optional[str] = Field(
        None,
        description="A signed URL for uploading the file part. It expires in 10 minutes.",
    )
