# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.multipartbase import MultipartBase
from pydantic import Field


class Multipart(MultipartBase):
    put_headers: Optional[List[MultipartHeaderBase]] = Field(
        None, description="MultipartHeader"
    )
