# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class MultipartHeaderBase(BaseModel):
    name: Optional[str] = Field(
        None, description="Required HTTP header field name for uploading."
    )
    value: Optional[str] = Field(
        None, description="Required HTTP header field value for uploading."
    )
