# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.myeventbase import MyEventBase


class MyEvent(MyEventBase):
    event: Optional[EventBase] = None
