# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class NotificationType(Enum):
    """
    The type of method to be notified by
    """
