# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class NotificationEventSubscriberBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *NotificationEventSubscriber* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *NotificationEventSubscriber*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *NotificationEventSubscriber*"
    )
    name: Optional[str] = Field(
        None,
        description="The User name added as a notification event subscriber to the NotificationEventSubscriber",
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *NotificationEventSubscriber* was last updated (as a ISO-8601 timestamp)",
    )
    user_id: Optional[int] = Field(
        None,
        description="The unique identifier for a User added as a notification event subscriber to the NotificationEventSubscriber",
    )
