# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.outstandingclientbalancebase import OutstandingClientBalanceBase
from pydantic import Field
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.currencybase import CurrencyBase
from clio_clients.models.billbase import BillBase


class OutstandingClientBalance(OutstandingClientBalanceBase):
    contact: Optional[ContactBase] = None
    currency: Optional[CurrencyBase] = None
    outstanding_bills: Optional[List[BillBase]] = Field(None, description="Bill")
