# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.participantbase import ParticipantBase


class Participant(ParticipantBase):
    avatar: Optional[AvatarBase] = None
