# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class Payload(BaseModel):
    custom_fields: Optional[Dict[str, Any]] = Field(
        None, description="Dynamic map of custom field values, e.g., date_of_incident"
    )
    display_number: Optional[str] = None
    id: Optional[int] = Field(None, description="The ID of the created matter")
    practice_area: Optional[str] = None
