# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.name.name2 import Name2


class PhoneNumberBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *PhoneNumber* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *PhoneNumber*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *PhoneNumber*"
    )
    name: Optional[Name2] = Field(None, description="The type of *PhoneNumber* it is")
    number: Optional[str] = Field(None, description="Contact's Phone Number")
    primary: Optional[bool] = Field(
        None, description="Whether it is default for this contact"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *PhoneNumber* was last updated (as a ISO-8601 timestamp)",
    )
