# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PicklistOptionBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *PicklistOption* was created (as a ISO-8601 timestamp)",
    )
    deleted_at: Optional[str] = Field(
        None,
        description="The time the *PicklistOption* was deleted (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *PicklistOption*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *PicklistOption*"
    )
    option: Optional[str] = Field(None, description="The value of the *PicklistOption*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *PicklistOption* was last updated (as a ISO-8601 timestamp)",
    )
