# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.polymorphiccustomratebase import PolymorphicCustomRateBase


class PolymorphicCustomRate(PolymorphicCustomRateBase):
    activity_description: Optional[PolymorphicCustomRateActivityDescriptionBase] = None
    group: Optional[PolymorphicCustomRateGroupBase] = None
    user: Optional[PolymorphicCustomRateUserBase] = None
