# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PolymorphicObjectBase(BaseModel):
    id: Optional[int] = Field(
        None, description="Unique identifier for the *PolymorphicObject*"
    )
    identifier: Optional[str] = Field(
        None, description="A string to identify the *PolymorphicObject*"
    )
    secondary_identifier: Optional[str] = Field(
        None, description="A secondary string to identify the *PolymorphicObject*"
    )
    tertiary_identifier: Optional[str] = Field(
        None, description="A tertiary string to identify the *PolymorphicObject*"
    )
    type: Optional[Type25] = Field(
        None, description="The type of the *PolymorphicObject*"
    )
