# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class PolymorphicCustomRateUserBase(BaseModel):
    enabled: Optional[bool] = Field(
        None, description="Whether the *User* is allowed to log in"
    )
    etag: Optional[str] = Field(None, description="ETag for the *User*")
    id: Optional[int] = Field(None, description="Unique identifier for the *User*")
    name: Optional[str] = Field(None, description="The full name of the *User*")
