# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.practicearea import PracticeArea


class PracticeAreaList(BaseModel):
    data: List[PracticeArea] = Field(..., description="PracticeArea List Response")
