# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PracticeAreaBase(BaseModel):
    category: Optional[Category] = Field(
        None,
        description="The practice area category associated with the *PracticeArea*",
    )
    code: Optional[str] = Field(None, description="The code of the *PracticeArea*")
    created_at: Optional[str] = Field(
        None,
        description="The time the *PracticeArea* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *PracticeArea*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *PracticeArea*"
    )
    name: Optional[str] = Field(None, description="The name of the *PracticeArea*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *PracticeArea* was last updated (as a ISO-8601 timestamp)",
    )
