# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.relationshipbase import RelationshipBase


class Relationship(RelationshipBase):
    contact: Optional[ContactBase] = None
    matter: Optional[MatterBase] = None
