# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class RelatedContactsBase(BaseModel):
    client_connect_user_id: Optional[int] = Field(
        None, description="The client connect ID of the contacts associated user"
    )
    contact_id: Optional[int] = Field(
        None, description="The id of the *RelatedContacts*"
    )
    created_at: Optional[str] = Field(
        None,
        description="The time the *RelatedContacts* was created (as a ISO-8601 timestamp)",
    )
    first_name: Optional[str] = Field(None, description="First name of the Person")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *RelatedContacts*"
    )
    initials: Optional[str] = Field(
        None, description="The initials of the *RelatedContacts*"
    )
    is_matter_client: Optional[bool] = Field(
        None,
        description="Whether or not the RelatedContacts is also the client of the matter",
    )
    last_name: Optional[str] = Field(None, description="Last name of the Person")
    middle_name: Optional[str] = Field(None, description="Middle name of the Person")
    name: Optional[str] = Field(
        None, description="The full name of the *RelatedContacts*"
    )
    prefix: Optional[str] = Field(
        None, description="The prefix of the *RelatedContacts* (Mr, Mrs, etc)"
    )
    primary_email_address: Optional[str] = Field(
        None, description="The primary email address of related contact"
    )
    primary_phone_number: Optional[str] = Field(
        None, description="The primary phone number of related contact"
    )
    title: Optional[str] = Field(
        None, description="The designated title of the *RelatedContacts*"
    )
    type: Optional[Type26] = Field(
        None, description="The type of the *RelatedContacts*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *RelatedContacts* was last updated (as a ISO-8601 timestamp)",
    )
