# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.relationshipbase import RelationshipBase
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.matterbase import MatterBase


class Relationship(RelationshipBase):
    contact: Optional[ContactBase] = None
    matter: Optional[MatterBase] = None
