# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.relatedcontacts import RelatedContacts


class RelatedContactsList(BaseModel):
    data: List[RelatedContacts] = Field(
        ..., description="RelatedContacts List Response"
    )
