# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class RelationshipBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *Relationship* was created (as a ISO-8601 timestamp)",
    )
    description: Optional[str] = Field(
        None, description="A detailed description of the *Relationship*"
    )
    etag: Optional[str] = Field(None, description="ETag for the *Relationship*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *Relationship*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *Relationship* was last updated (as a ISO-8601 timestamp)",
    )
