# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.reminderbase import ReminderBase
from clio_clients.models.notificationmethodbase import NotificationMethodBase
from clio_clients.models.polymorphicobjectbase import PolymorphicObjectBase


class Reminder(ReminderBase):
    notification_method: Optional[NotificationMethodBase] = None
    subject: Optional[PolymorphicObjectBase] = None
