# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.reportpreset import ReportPreset


class ReportPresetList(BaseModel):
    data: List[ReportPreset] = Field(..., description="ReportPreset List Response")
