# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.reportschedule import ReportSchedule


class ReportScheduleShow(BaseModel):
    data: ReportSchedule
