# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.reportpresetbase import ReportPresetBase


class ReportPreset(ReportPresetBase):
    report_schedule: Optional[ReportScheduleBase] = None
