# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.reportpreset import ReportPreset


class ReportPresetShow(BaseModel):
    data: ReportPreset
