# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.report import Report


class ReportList(BaseModel):
    data: List[Report] = Field(..., description="Report List Response")
