# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.servicetype import ServiceType


class ServiceTypeShow(BaseModel):
    data: ServiceType
