# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class ServiceTypeList(BaseModel):
    data: List[ServiceType] = Field(..., description="ServiceType List Response")
