# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class State3(Enum):
    """
    A text description of what the automation is currently doing
    """
