# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class StatuteOfLimitationsComputeResponse(BaseModel):
    due_at: str = Field(
        ..., description="The calculated statute of limitations due date."
    )
