# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class State1(Enum):
    """
    The state of the payment (authorized, completed, failed, etc).
    """
