# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class StatuteOfLimitationsComputeRequest(BaseModel):
    date_of_incident: str = Field(
        ..., description="The date when the incident occurred."
    )
