# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class State(Enum):
    """
    The billing state the *Bill* is in
    """
