# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class State2(Enum):
    """
    The current state of the DocumentArchive.
    """
