# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class SubscriptionType1(Enum):
    """
    The subscription type of the *User*
    """
