# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.tasktemplatelistbase import TaskTemplateListBase


class TaskTemplateList(TaskTemplateListBase):
    creator: Optional[UserBase] = None
    practice_area: Optional[PracticeAreaBase] = None
