# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class TaskTemplateListInstanceBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *TaskTemplateListInstance* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(
        None, description="ETag for the *TaskTemplateListInstance*"
    )
    id: Optional[int] = Field(
        None, description="Unique identifier for the *TaskTemplateListInstace*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *TaskTemplateListInstace* was last updated (as a ISO-8601 timestamp)",
    )
