# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class TaskShow(BaseModel):
    data: Task = Field(..., description="Task")
