# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List, Optional

from clio_clients.models.tasktemplatebase import TaskTemplateBase
from pydantic import Field
from clio_clients.models.userbase import UserBase
from clio_clients.models.cascadingtasktemplatebase import CascadingTaskTemplateBase
from clio_clients.models.remindertemplatebase import ReminderTemplateBase
from clio_clients.models.tasktemplatelistbase import TaskTemplateListBase
from clio_clients.models.tasktypebase import TaskTypeBase
from clio_clients.models.userbase import UserBase


class TaskTemplate(TaskTemplateBase):
    assignee: Optional[UserBase] = None
    cascading_source: Optional[CascadingTaskTemplateBase] = None
    reminder_templates: Optional[List[ReminderTemplateBase]] = Field(
        None, description="ReminderTemplate"
    )
    task_template_list: Optional[TaskTemplateListBase] = None
    task_type: Optional[TaskTypeBase] = None
    template_creator: Optional[UserBase] = None
