# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.tasktemplatelist import TaskTemplateList


class TaskTemplateListList(BaseModel):
    data: List[TaskTemplateList] = Field(
        ..., description="TaskTemplateList List Response"
    )
