# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.tasktype import TaskType


class TaskTypeList(BaseModel):
    data: List[TaskType] = Field(..., description="TaskType List Response")
