# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from clio_clients.models.tasktemplatebase import TaskTemplateBase

class TaskTemplate(TaskTemplateBase):
    assignee: Optional[UserBase] = None
    cascading_source: Optional[CascadingTaskTemplateBase] = None
    reminder_templates: Optional[List[ReminderTemplateBase]] = Field(
        None, description="ReminderTemplate"
    )
    task_template_list: Optional[TaskTemplateListBase] = None
    task_type: Optional[TaskTypeBase] = None
    template_creator: Optional[UserBase] = None
