# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.taskbase import TaskBase


class Task(TaskBase):
    pass


Task.model_rebuild()  # <-- Add this at the end of the file
