# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class TaxSetting(Enum):
    """
    The option denoting whether primary tax, secondary tax, or both is applied to an expense entry.
    """
