# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.textsnippet import TextSnippet


class TextSnippetList(BaseModel):
    data: List[TextSnippet] = Field(..., description="TextSnippet List Response")
