# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class TextSnippetBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *TextSnippet* was created (as a ISO-8601 timestamp)",
    )
    etag: Optional[str] = Field(None, description="ETag for the *TextSnippet*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *TextSnippet*"
    )
    phrase: Optional[str] = Field(
        None, description="The phrase the abbreviation should be expanded to"
    )
    snippet: Optional[str] = Field(
        None, description="The abbreviation that should be expanded"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *TextSnippet* was last updated (as a ISO-8601 timestamp)",
    )
    whole_word: Optional[bool] = Field(
        None,
        description="Whether the *TextSnippet* abbreviation requires a space after it has been entered to expand to a phrase",
    )
