# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from clio_clients.models.trustlineitembase import TrustLineItemBase
from clio_clients.models.billbase import BillBase
from clio_clients.models.contactbase import ContactBase
from clio_clients.models.matterbase import MatterBase


class TrustLineItem(TrustLineItemBase):
    bill: Optional[BillBase] = None
    client: Optional[ContactBase] = None
    matter: Optional[MatterBase] = None
