# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class TrustLineItemList(BaseModel):
    data: List[TrustLineItem] = Field(..., description="TrustLineItem List Response")
