# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class TrustLineItemBase(BaseModel):
    created_at: Optional[str] = Field(
        None,
        description="The time the *TrustLineItem* was created (as a ISO-8601 timestamp)",
    )
    date: Optional[str] = Field(
        None, description="The date of the *TrustLineItem* (as a ISO-8601 date)"
    )
    etag: Optional[str] = Field(None, description="ETag for the *TrustLineItem*")
    id: Optional[int] = Field(
        None, description="Unique identifier for the *TrustLineItem*"
    )
    note: Optional[str] = Field(None, description="Note for the *TrustLineItem*")
    total: Optional[float] = Field(
        None, description="The total amount for the *TrustLineItem*"
    )
    updated_at: Optional[str] = Field(
        None,
        description="The time the *TrustLineItem* was last updated (as a ISO-8601 timestamp)",
    )
