# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class UiReference(Enum):
    """
    UI reference location within Clio where the link will be displayed.
    """
