# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.utbmsset import UtbmsSet


class UtbmsSetList(BaseModel):
    data: List[UtbmsSet] = Field(..., description="UtbmsSet List Response")
