# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field
from clio_clients.models.type.type27 import Type27


class UtbmsCodeBase(BaseModel):
    code: Optional[str] = Field(None, description="The UTBMS code for the *UtbmsCode*")
    created_at: Optional[str] = Field(
        None,
        description="The time the *UtbmsCode* was created (as a ISO-8601 timestamp)",
    )
    description: Optional[str] = Field(
        None, description="The UTBMS description for the *UtbmsCode*"
    )
    etag: Optional[str] = Field(None, description="ETag for the *UtbmsCode*")
    id: Optional[int] = Field(None, description="Unique identifier for the *UtbmsCode*")
    name: Optional[str] = Field(None, description="The name of the *UtbmsCode*")
    type: Optional[Type27] = Field(None, description="The type of the *UtbmsCode*")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *UtbmsCode* was last updated (as a ISO-8601 timestamp)",
    )
    utbms_set_id: Optional[int] = Field(None, description="Set id for the *UtbmsCode*")
