# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field
from clio_clients.models.webhook import Webhook


class WebhookList(BaseModel):
    data: List[Webhook] = Field(..., description="Webhook List Response")
