# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSiteBase(BaseModel):
    address: Optional[str] = Field(None, description="The address of the *WebSite*")
    created_at: Optional[str] = Field(
        None, description="The time the *WebSite* was created (as a ISO-8601 timestamp)"
    )
    default_web_site: Optional[bool] = Field(
        None, description="Whether it is the default for this contact"
    )
    etag: Optional[str] = Field(None, description="ETag for the *WebSite*")
    id: Optional[int] = Field(None, description="Unique identifier for the *WebSite*")
    name: Optional[Name3] = Field(None, description="The type of *WebSite* it is")
    updated_at: Optional[str] = Field(
        None,
        description="The time the *WebSite* was last updated (as a ISO-8601 timestamp)",
    )
