# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from clio_clients.models.eventmetricsbase import EventMetricsBase


class EventMetrics(EventMetricsBase):
    pass
