# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from pydantic import BaseModel
from clio_clients.models.event.eventmetrics import EventMetrics


class EventMetricsShow(BaseModel):
    data: EventMetrics
