# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class EventBase(BaseModel):
    description: Optional[str] = Field(
        None,
        description="Description or additional information about the event (e.g. Matter Description)",
    )
    description_url: Optional[str] = Field(
        None,
        description="Target URL that will be opened if the user clicks on the event description",
    )
    etag: Optional[str] = Field(None, description="ETag for the *Event*")
    icon: Optional[str] = Field(
        None, description="Font Awesome icon to display (without the fa- prefix)"
    )
    id: Optional[int] = Field(None, description="Unique identifier for the *Event*")
    message: Optional[str] = Field(
        None, description="Concise headline message describing the event"
    )
    mobile_icon: Optional[str] = Field(
        None, description="Icon to be displayed in the mobile app"
    )
    occurred_at: Optional[str] = Field(None, description="When the event occurred")
    primary_detail: Optional[str] = Field(
        None,
        description="Optional additional information about the event (e.g. Matter Client, Document Author)",
    )
    primary_detail_url: Optional[str] = Field(
        None,
        description="Target URL that will be opened if the user clicks on the primary detail",
    )
    secondary_detail: Optional[str] = Field(
        None,
        description="Optional additional information about the event (e.g. Matter Status, Document Size)",
    )
    secondary_detail_url: Optional[str] = Field(
        None,
        description="Target URL that will be opened if the user clicks on the secondary detail",
    )
    subject_id: Optional[int] = Field(
        None, description="Id of the subject that triggered the notification"
    )
    subject_type: Optional[str] = Field(
        None,
        description="The type of subject that triggered the notification (e.g. Matter, Document)",
    )
    title: Optional[str] = Field(
        None,
        description="The title or subject of the event (e.g. Matter Number, Document Title)",
    )
    title_url: Optional[str] = Field(
        None,
        description="Target URL that will be opened if the user clicks on the event title",
    )
