# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

class EventMetricsBase(BaseModel):
    unread_client_portal_messages: Optional[int] = Field(
        None,
        description="The number of unread client portal messages for the current user",
    )
    unread_mobile_events: Optional[int] = Field(
        None,
        description="The number of unread mobile event notifications for the current user",
    )
    unread_secure_messages: Optional[int] = Field(
        None, description="The number of unread secure messages for the current user"
    )
    unread_text_messages: Optional[int] = Field(
        None, description="The number of unread text messages for the current user"
    )
    unread_web_events: Optional[int] = Field(
        None,
        description="The number of unread web event notifications for the current user",
    )
