# generated by datamodel-codegen:
#   filename:  openapi_sdk.yaml

from __future__ import annotations

from enum import Enum


class Event1(Enum):
    created = "created"
    updated = "updated"
    deleted = "deleted"
    matter_opened = "matter_opened"
    matter_pended = "matter_pended"
    matter_closed = "matter_closed"
